name: Build, Bundle, Release Go Plugin

on:
  push:
    branches: [ master ]

jobs:
  build:

    environment: dev
    runs-on: luminosita-ubuntu

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go v1.21.8
        with:
          go-version: '1.21.8'
        uses: actions/setup-go@v5
      - name: Copy Env Files
        run: cp .env.example .env
        
      - name: Bundle Go Plugin
        run: DOCKER_USER=root make go-bundle
      - name: List files in the working directory
        run: |
          ls tyk/bundle/
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Upload Plugin to Nexus
        run: curl -v -k -u admin:${{ secrets.NEXUS_PASSWORD }} --upload-file tyk/bundle/bundle.zip ${{ vars.NEXUS_TYK_REPO_URL }}/net/emisia/grpc/$VERSION/grpc-$VERSION-$SNAPSHOT.zip
        env:
          SNAPSHOT: SNAPSHOT-${{ steps.date.outputs.date }}
          VERSION: "0.0.1"
